name: dart_random_choice
description: A library for generating a random choice from an iterable.
version: 0.2.0
homepage: https://github.com/kmorkos/dart_random_choice
repository: https://github.com/kmorkos/dart_random_choice
issue_tracker: https://github.com/kmorkos/dart_random_choice/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.22.1
