name: dart_random_choice
description: A library for generating a random choice from an iterable.
version: 0.1.0-nullsafety.0
author: Kirollos Morkos <kman2121@gmail.com>
homepage: https://github.com/kmorkos/dart_random_choice
repository: https://github.com/kmorkos/dart_random_choice
issue_tracker: https://github.com/kmorkos/dart_random_choice/issues
documentation:

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  test: ^1.16.0-nullsafety.16
