name: dart_random_choice
description: A library for generating a random choice from an iterable.
version: 0.0.1
author: Kirollos Morkos <kman2121@gmail.com>
homepage: https://github.com/kmorkos/dart_random_choice

dependencies:

dev_dependencies:
  test: ^1.6.1

